### ISSUE TITLE
HTTP1/HTTP2 Proxy errors with CONNECT

### ISSUE THREAD

**Issue by arbarlow** [grpc/grpc-go#1243]
I posted this over at the Linkerd repo, but thought it would be useful to bring it up here too and see if we can resolve it somehow.

**Desired behaviour:**
Using linkerd as a http2 proxy with a gRPC client and gRPC server works transparently to the client and server.

**Actual behaviour:**
gRPC client attempts to do a http 1.0 `CONNECT` which fails.

**Setup**
gRPC Go: 1.4.0
Using the gRPC go[ 'hello world' examples](https://github.com/grpc/grpc-go/tree/master/examples/helloworld) (modify the client to send requests to 'world' instead of 'localhost'), then running..

`http_proxy=localhost:4140 go run main.go`

This causes the client to hang, as it will issue a http `CONNECT` to connect to the proxy, but gets no reply.

Wireshark shows this like the following..

![screen shot 2017-05-12 at 15 28 48](https://cloud.githubusercontent.com/assets/106357/26002502/c1a296ea-3727-11e7-86bf-a327b9ff6448.png)

Commenting out this line in gRPC-Go works as it uses the proxy, but skips the `CONNECT`: https://github.com/grpc/grpc-go/blob/master/proxy.go#L141

My linkerd config (essentially, it created a simple http2 based router/proxy) is the following..

```yaml
admin:
  port: 9990

routers:
- protocol: h2
  label: proxy
  experimental: true
  identifier:
    kind: io.l5d.header.token
  dtab: /svc => /$/inet/192.168.0.10/50051
  servers:
  - ip: 0.0.0.0
    port: 4140
```

`192.168.0.10/50051` being where my Go server is located

In summary, it would be useful to resolve this by either changing the way proxies work/skipping CONNECT is some circumstances or something similar. A timeout for the CONNECT should also probably be added. I'm happy to code the solution but I feel a discussion is definitely needed first!
