### ISSUE TITLE
Running Envoy for load-balancing gRPC golang services

### ISSUE THREAD

**Issue by ArkadyB** [grpc/grpc-go#1901]
Hi,

I have a set of Golang microservices all communicating to each other and client application over gRPC. Now id like to run into load balancing over Envoy, but unfortunately Envoy demos/examples/docs seem to lack this part not showing anythin about routing of gRPC calls based on either method name or service name. I was not able to find anything meaningful rather than H1 -> H2 routing. 

If there is someone with experience running gRPC services mesh using Envoy, would you share some basic setup configuration example?

To route call over Envoy to locally running gRPC service i use:
 
```
admin:
  access_log_path: /tmp/admin_access.log
  address:
    socket_address: { address: 0.0.0.0, port_value: 9901 }

static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address: { address: 0.0.0.0, port_value: 30271 }
    filter_chains:
    - filters:
      - name: envoy.http_connection_manager
        config:
          stat_prefix: ingress_http
          codec_type: AUTO
          route_config:
            name: local_route
            virtual_hosts:
            - name: service1_grpc
              domains: ["*"]
              routes:
              - match: { prefix: "/" }
                route: { cluster: service1_grpc }
          http_filters:
          - name: envoy.router
            config: {}
  clusters:
  - name: service1_grpc
    connect_timeout: 25s
    type: STRICT_DNS
    lb_policy: ROUND_ROBIN
    dns_lookup_family: V4_ONLY
    http2_protocol_options: { }
    hosts: [{ socket_address: { address: 127.0.0.1, port_value: 30270 }}]
```

But now assume i have "service1_grpc" to make calls to "service2_grpc" where service2 has its own Envoy configuration similar to one above. How do i make configuration for all gRPC calls from service1 to service2 to be properly routed?

Something like:
```
   route_config:
            name: service2_route
            virtual_hosts:
            - name: service2_grpc
              domains: ???
              routes:
              - match: ???
                route: { cluster: service2_grpc }
```
