### ISSUE TITLE
Questions about send Google credentials through UDS

### ISSUE THREAD

**Issue by quanjielin** [grpc/grpc-go#2235]
### What version of gRPC are you using?
server is built on gRPC/go
client is envoy built on gRPC/c++

### What did you do?
Our scenario is envoy(client based on gRPC/C++) needs to send Google credentials(some GKE token) to server(based on gRPC/go) through UDS(unix domain socket), the client side config is put below.

Our questions are -
1. Does grpc-go already supported sending google credential through UDS securely ?
2. If yes for 1, is TLS setup required(setting up channel_credentials)  ?

```
grpc_services {
  google_grpc {
    target_uri: "unix:/var/run/sds/uds_path"
    channel_credentials {
      ssl_credentials {
        root_certs {
          filename: "/etc/istio/nodeagent-root-cert.pem"
        }
      }
    }
    call_credentials {
      google_compute_engine {
      }
    }
    stat_prefix: "test"
  }
}
```

3. I gave a try by setting up TLS without call_credentials, envoy(client) side config looks like
```
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/var/run/sds/uds_path
                    channel_credentials:
                      ssl_credentials:
                        root_certs:
                          filename: /etc/istio/nodeagent-root-cert.pem

```
server side error
```
ransport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:30:37.250966Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF"
2018-07-21T01:31:42.641122Z	info	grpc: Server.Serve failed to create ServerTransport: connection error: desc = "transport: http2Server.HandleStreams failed to receive the preface from client: EOF
```

server side error is thrown from
https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http2_server.go#L264

4. if I write a simple grpc client using go to setup channel cred(TLS), server side didn't see this error; looks like gRPC/go client takes care of clientPreface
https://github.com/grpc/grpc-go/blob/11b582728a13ef54e14e4fa930d693de2e32420f/internal/transport/http2_client.go#L274

**Comment by qiwzhang** [comment]
@lizan, @PiotrSikora,  @htuch, could you help double checking the channel credentials for google_grpc config?

**Comment by quanjielin** [comment]
[envoy_grpc.log](https://github.com/grpc/grpc-go/files/2220587/envoy_grpc.log)

@htuch attached log file, let's know if it's good enough

**Comment by quanjielin** [comment]
/cc @yihuazhang
we built an envoy binary which takes https://github.com/grpc/grpc/pull/15909, and use this envoy to send request to server in GKE env.

1. server could receive get request from envoy client(with client config below)
```
    tls_context:
      common_tls_context:
        tls_certificate_sds_secret_configs:
        - name: "spiffe://cluster.local/ns/default/sa/default"
          sds_config:
            api_config_source:
              api_type: GRPC
              grpc_services:
              - google_grpc:
                  stat_prefix: test
                  target_uri: unix:/var/run/sds/uds_path
              refresh_delay: 60s
```

2. server didn't receive request from envoy client if call_credentials is set in client config
```
      tls_context:
        common_tls_context:
          tls_certificate_sds_secret_configs:
          - name: "spiffe://cluster.local/ns/default/sa/default"
            sds_config:
              api_config_source:
                api_type: GRPC
                grpc_services:
                - google_grpc:
                    stat_prefix: test
                    target_uri: unix:/var/run/sds/uds_path
                    call_credentials:
                      google_compute_engine: {}
                refresh_delay: 60s
```

@yihuazhang, no channel_cred/TLS is needed if envoy takes your PR(https://github.com/grpc/grpc/pull/15909), is that correct ?
