### ISSUE TITLE
Can I start auth proxy?

### ISSUE THREAD

**Issue by arturgspb** [grpc/grpc-go#2261]
I have python and java grpc microservice.

Need start grcp proxy server with JWT authenticate as facade proxy server.
For example in the end I need this schema:

1) Client -- GRPC (not REST) request with JWT in Header --> 

2) ProxyFacade (decoding JWT and add to Context UserID and scopes) --- Request Python or Java backend ---> 

3) Python Backed (read UserID and working without JWT decoding)

How I can do it?

**Comment by lyuxuan** [comment]
Hi @arturgspb, you could use a HTTP2 proxy as the auth proxy. The proxy examines the incoming header frame and decodes the header fields. Then use the JWT token key (depending on the grpc per RPC credential implementation you use, e.g. [here](https://github.com/grpc/grpc-go/blob/956d689a245da51ffe6188643299ca07ffa28e44/credentials/oauth/oauth.go#L137) uses "authorization" as the key for JWT token) to find the corresponding JWT token in the decoded header fields. After you verify the token, you can generate a new header frame with JWT header field removed and fields like UserID and scopes added.Thanks! Please let us know if you need further info.

**Comment by arturgspb** [comment]
@lyuxuan, thx a lot!

From similar programs I found only Google Cloud Endpoints, where not necessarily SSL and some complicated proxy configuration.

But there are no real simple working examples of how to do without using Google Cloud Endpoints.
There are examples where I need to register a service from a protobuf file on a proxy server, i.e. where the proxy should know which services it proxy, but it does not suit me.

I would be very helped by a simple example of one file in which the structure generated from the proto file would not be used.

For example, something with the use of "github.com/google/tcpproxy" or something like that. It is important that the proxy does not know what data and service/method  proxy, but simply read and write the headers, and if unsuccessful authorization would return an error and would not proxy to the backend.

I'm very sorry for the machine translation through google translate, I hope my problem is clear to you and you will help me.

Thank you in advance!

**Comment by lyuxuan** [comment]
I do not know about any go library that does HTTP2 proxy, you may need to write your own.

FYI, nginx and envoy supports proxying grpc, you may want to look into them. Please let us know if you need any help. Thank you!

**Comment by arturgspb** [comment]
I decided my question.
You can run google endpoints api in your local cluster and check through JWT accesses and with RPS quotas!

Your actions:

1) Create a project on google cloud, add a service account
2) Generate api_descriptor.pb from your proto files and upload to google cloud endpoint
3) Make api_config.yaml and specify there how to check the token
4) Launch in your cluster image gcr.io/endpoints-release/endpoints-runtime:1 with the configured backend

Documentation:

- https://cloud.google.com/endpoints/docs/grpc/configure-endpoints
- https://cloud.google.com/endpoints/docs/grpc/running-esp-localdev
- https://cloud.google.com/endpoints/docs/openapi/authenticating-users#configuring_extensible_service_proxy_to_support_client_authentication
- https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/endpoints/getting-started-grpc

Example configs:

*api_config.yaml*
```yaml
# https://cloud.google.com/endpoints/docs/grpc/quotas-configure

type: google.api.Service
config_version: 3

name: YOUR_API_NAME.endpoints.YOUR_PROJECT_ID.cloud.goog

title: YOUR_API_NAME gRPC API
apis:
- name: helloapi.HelloService


usage:
  rules:
  - selector: "*"
    allow_unregistered_calls: true

authentication:
  # https://github.com/googleapis/googleapis/blob/master/google/api/auth.proto
  providers:
  - id: google_service_account
    issuer: "jwt-client.endpoints.sample.google.com"
    audiences: "YOUR_API_NAME.endpoints.YOUR_PROJECT_ID.cloud.goog"
    jwks_uri: "https://www.googleapis.com/robot/v1/metadata/x509/test-esp@YOUR_PROJECT_ID.iam.gserviceaccount.com"
  rules:
  - selector: "*"
    requirements:
      - provider_id: google_service_account

metrics:
  - name: "ReadCallLimits"
    display_name: "Read requests"
    value_type: INT64
    metric_kind: DELTA
quota:
  limits:
    - name: "read-limit"
      metric: "ReadCallLimits"
      unit: "1/min/{project}"
      values:
        STANDARD: 100
  metric_rules:
    - selector: "*"
      metric_costs:
        "ReadCallLimits": 1
```


*deployment.yaml*
```yaml
# https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/endpoints/kubernetes/k8s-grpc-bookstore.yaml

apiVersion: v1
kind: Service
metadata:
  name: grpc-hello
spec:
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: grpc-hello
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grpc-hello
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grpc-hello
    spec:
      volumes:
        - name: service-account-creds
          secret:
            secretName: service-account-creds
      imagePullSecrets:
        - name: registry-secret
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http2_port=9000",
          "--backend=grpc://127.0.0.1:50051",
          "--service=YOUR_API_NAME.endpoints.YOUR_PROJECT_ID.cloud.goog",
          "--service_account_key=/etc/nginx/creds/service-account-creds.json",
          "--rollout_strategy=managed",
        ]
        ports:
          - containerPort: 9000
        volumeMounts:
          - mountPath: /etc/nginx/creds
            name: service-account-creds
            readOnly: true
      - name: python-grpc-hello
        image: YOUR_BACKEND_IMAGE
        ports:
          - containerPort: 50051
```
