### ISSUE TITLE
Client-side load balancing uses the wrong port

### ISSUE THREAD

**Issue by piotrkowalczuk** [grpc/grpc-go#2619]
### What version of gRPC are you using?
~v1.17.0 - `df014850f6dee74ba2fc94874043a9f3f75fbfd8` (works)
^v1.18.0 - `a02b0774206b209466313a0b525d2c738fe407eb` (does not)

### What version of Go are you using (`go version`)?
go version go1.11.1 darwin/amd64

### What operating system (Linux, Windows, …) and version?
alpine:latest

### What did you do?
One of the services that I'm working on is making client-side load balancing using DNS resolver (in kubernetes). It tries to connect to another service using an address like `dns:///SERVICE_NAME-headless`. It worked just fine until I changed gRPC version from `v1.17.0` to `v1.18.0`. Connection code looks like (plus some interceptors and stat handler):

```
conn, err := grpc.DialContext(ctx, addr,
        grpc.WithInsecure(),
        grpc.WithBlock(),
        grpc.WithDisableServiceConfig(),
        grpc.WithBalancerName(roundrobin.Name),
        grpc.WithUserAgent(vars.Subsystem),
)
```

### What did you expect to see?
Proper log messages produced by `grpclog` package with no IP duplicates being present.

### What did you see instead?
```
ccResolverWrapper: sending new addresses to cc: [{<IP_ADDR_1>:8080 1 6663316364376161.SERVICE_NAME-headless.staging.svc.cluster.local. <nil>} {<IP_ADDR_2>:8080 1 6333356261396666.SERVICE_NAME-headless.staging.svc.cluster.local. <nil>} {<IP_ADDR_1>:443 0 <nil>} {<IP_ADDR_2>:443 0 <nil>}]
base.baseBalancer: got new resolved addresses: [{< IP_ADDR_1>:443 0  <nil>} {<IP_ADDR_2>:443 0  <nil>}]
```

As you can see each IP address is present twice. Once with proper port `8080` and once with `443` (default port I guess).

EDIT:
`v1.17.0` prints similar output but at the end is able to connect. Maybe the difference is that `v1.17.0` is using 4 addresses (2 invalid => 2 warning logs) and `v1.18.0` is using 2 addresses (both invalid).

#### grpc diff
https://github.com/grpc/grpc-go/compare/df014850f6dee74ba2fc94874043a9f3f75fbfd8...master
#### dig output
```
$ dig _grpclb._tcp.SERVICE_NAME-headless.staging.svc.cluster.local SRV
;; QUESTION SECTION:
;_grpclb._tcp.SERVICE_NAME-headless.staging.svc.cluster.local. IN	SRV

;; ANSWER SECTION:
_grpclb._tcp.SERVICE_NAME-headless.staging.svc.cluster.local. 30	IN SRV 10 50 8080 6333356261396666.SERVICE_NAME-headless.staging.svc.cluster.local.
_grpclb._tcp.SERVICE_NAME-headless.staging.svc.cluster.local. 30	IN SRV 10 50 8080 6663316364376161.SERVICE_NAME-headless.staging.svc.cluster.local.

;; ADDITIONAL SECTION:
6333356261396666.SERVICE_NAME-headless.staging.svc.cluster.local. 30 IN A IP_ADDR_1
6663316364376161.SERVICE_NAME-headless.staging.svc.cluster.local. 30 IN A IP_ADDR_2
```

#### kubernetes headless service config

```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-30T10:13:31Z
  labels:
    app: SERVICE_NAME
    chart: SERVICE_NAME-CHART_VERSION
    fullname: SERVICE_NAME-SERVICE_NAME
    heritage: Tiller
    release: SERVICE_NAME
  name: SERVICE_NAME-headless
  namespace: staging
  selfLink: /api/v1/namespaces/staging/services/SERVICE_NAME-headless
spec:
  clusterIP: None
  ports:
  - name: grpclb
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: SERVICE_NAME
    release: SERVICE_NAME
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
