### ISSUE TITLE
is grpc xds support istiod as xds server?

### ISSUE THREAD

**Issue by carolove** [grpc/grpc-go#4150]
i found there is a example about  grpc xds.
i use this example at istiod 1.7, and found it doesn't work.
```json
{
    "xds_servers": [
      {
        "server_uri": "10.0.71.150:30549", // this is istiod's nodeport addr
        "channel_creds": [
          {
            "type": "insecure"
          }
        ]      
      }
    ],
    "node": {
      "id": "sidecar~10.1.0.156~nodeapp-85985696d9-8zq94.default~default.svc.cluster.local",
      "cluster":"nodeapp.default",
      "metadata": {
            "CLUSTER_ID": "Kubernetes",
            "INTERCEPTION_MODE":  "REDIRECT",
            "ISTIO_VERSION": "unknow",
            "LABELS": {
                "istio":  "ingressgateway"
            }
        }
    }
}
```

and  grpc xds example client call like below
go run client/main.go  "hello xds" xds:///0.0.0.0_28880
0.0.0.0_28880 is a istio xds outbound listener 

i construct istio xds by below CRs:
```yaml
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: dubbo-proxy
  namespace: default
spec:
  hosts:
  - app.io.nodeapp.proxy
  location: MESH_INTERNAL
  ports:
  - name: xxx-http
    number: 28880
    protocol: HTTP
    targetPort: 50051
  resolution: STATIC
  workloadSelector:
    labels:
      app: app.io.nodeapp.proxy
---
apiVersion: networking.istio.io/v1beta1
kind: WorkloadEntry
metadata:
  name: proxy-2
  namespace: default
spec:
  address: 10.0.71.150
  labels:
    app: app.io.nodeapp.proxy
```

and i get a error when call istio for xds

in code 
```golang

func processListener(lis *v3listenerpb.Listener) (*ListenerUpdate, error) {
	if lis.GetApiListener() != nil {
		return processClientSideListener(lis)
	}
	return processServerSideListener(lis)
}
```
file xds/internal/client/client_xds.go
lis GetApiListener is nil , grpc xds can't found correct xds listener form pilot xds server,
in pilot xds server there isn't ApiListener

how can i run grpc xds with istiod?
