### ISSUE TITLE
Deal with healthchecks from cloud loadbalancers - EOF

### ISSUE THREAD

**Issue by wiardvanrij** [grpc/grpc-go#4234]
Please see the FAQ in our main README.md before submitting your issue.

### Use case(s) - what problem will this feature solve?
It will resolve de-cluttering of logs by not having the following error anymore:
```
"transport: http2Server.HandleStreams failed to receive the preface from client: EOF\"
```
on systems that use a cloud loadbalancer, for example via Kubernetes.

### Proposed Solution

I'm not experienced enough to know if this resolves the issue, but the check on this line: https://github.com/grpc/grpc-go/blob/master/internal/transport/http2_server.go#L275 should perhaps be moved after line 266 directly. To somewhat silently ignore this EOF. 

This is was already the case in 2017, as you can see that this comment changed it's behaviour: https://github.com/grpc/grpc-go/pull/1646/commits/1739d3b1307921f1f278a349b94ce7edbbd9035c

```
// Only log if it isn't a simple tcp accept check (ie: tcp balancer doing open/close socket)	
		if err != io.EOF {
                 // SNIP
```

### Alternatives Considered
Perhaps applications that implement grpc could deal with these tcp checks from cloud loadbalancers. I'm not sure.

### Additional Context

This error/info happens if we create an external service in Kubernetes like so:

```
service:
    annotations:
      external-dns.alpha.kubernetes.io/hostname: redacted
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
    type: LoadBalancer
    grpc:
      port: 14250
```

which then automatically creates a cloud loadbalancer with a nodeport exposed as such:

```
spec:
  clusterIP: redacted
  externalTrafficPolicy: Cluster
  ports:
  - name: grpc
    nodePort: 30570
    port: 14250
    protocol: TCP
    targetPort: grpc
```

This results in healthchecks on the cloud loadbalancer as such:

![image](https://user-images.githubusercontent.com/5786097/109676051-a0437700-7b78-11eb-8656-fa2047c319f8.png)

And this causes, depending on how many nodes you run, on multiple warnings per second. 

Relates to https://github.com/jaegertracing/jaeger/issues/2172 I believe
