### ISSUE TITLE
Add support for String Matcher in Header Matching

### ISSUE THREAD

**Issue by costinm** [grpc/grpc-go#6226]
```
core] [Channel #7] ccResolverWrapper: reporting error to cc: received route is invalid: route name:"istio-safe-stability.v1--testecho.0"  match:{prefix:"/"  case_sensitive:{value:true}  headers:{name:"x-istio-cluster"  string_match:{exact:"outbound|8080||v1--testecho.istio-safe-stability.svc.cluster.local"}}}  route:{cluster:"outbound|8080||v1--testecho.istio-safe-stability.svc.cluster.local"  cluster_not_found_response_code:INTERNAL_SERVER_ERROR  timeout:{}  retry_policy:{retry_on:"connect-failure,refused-stream,unavailable,cancelled,retriable-status-codes"  num_retries:{value:2}  retry_host_predicate:{name:"envoy.retry_host_predicates.previous_hosts"  typed_config:{type_url:"type.googleapis.com/envoy.extensions.retry.host.previous_hosts.v3.PreviousHostsPredicate"}}  host_selection_retry_max_attempts:5  retriable_status_codes:503}  max_stream_duration:{max_stream_duration:{}}}  metadata:{filter_metadata:{key:"istio"  value:{fields:{key:"config"  value:{string_value:"/apis/networking.istio.io/v1alpha3/namespaces/istio-safe-stability/virtual-service/v1--testecho-0-istio-autogenerated-k8s-gateway"}}}}}  decorator:{operation:"v1--testecho.istio-safe-stability.svc.cluster.local:8080/*"} has an unrecognized header matcher: &{StringMatch:exact:"outbound|8080||v1--testecho.istio-safe-stability.svc.cluster.local"}
```

This is produced by a standard HttpRoute -

```
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  - group: gateway.networking.k8s.io
    kind: Service
    name: echo
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: v1--testecho
      port: 8080
      weight: 1
    matches:
    - headers:
      - name: x-istio-cluster
        type: Exact
        value: outbound|8080||v1--testecho.istio-safe-stability.svc.cluster.local
      path:
        type: PathPrefix
        value: /
```

NOTE: if you are reporting is a potential security vulnerability or a crash,
please follow our CVE process at
https://github.com/grpc/proposal/blob/master/P4-grpc-cve-process.md instead of
filing an issue here.

Please see the FAQ in our main README.md, then answer the questions below
before submitting your issue.

### What version of gRPC are you using?

v1.56.0-dev ( tried on older versions too )

### What did you do?
If possible, provide a recipe for reproducing the error.
