### ISSUE TITLE
​​Request for Header Manipulation Support in gRPC xDS​​

### ISSUE THREAD

**Issue by acynothia** [grpc/grpc-go#8262]
Would it be possible to consider adding support for request header manipulation in gRPC xDS?

https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-virtualhost

This capability would be particularly valuable for implementing common traffic management strategies such as canary deployments and blue-green releases. For instance, in scenarios like the shelf service example below, we could use HTTP headers to "color" traffic flows. When inbound traffic lacks such markers, primary routing rules could distribute traffic by weight while simultaneously adding header-based labels (to prevent unintended traffic shifts between canary and non-canary paths in long call chains). For pre-labeled traffic, the system would honor existing header values.

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shelf-internal
  namespace: app
spec:
  hosts:
    - shelf-internal.private
  gateways:
    - istio-system/inbound-internal-gateway
  http:
    - name: shelf-canary
      match:
        - headers:
            X-Canary:
              exact: "true"
      route:
        - destination:
            host: shelf.app.svc.cluster.local
            subset: canary

    - name: shelf-stable
      match:
        - headers:
            X-Canary:
              exact: "false"
      route:
        - destination:
            host: shelf.app.svc.cluster.local
            subset: stable

    - name: primary
      route:
        - destination:
            host: shelf.app.svc.cluster.local
            subset: stable
          headers:
            request:
              set:
                X-Canary: "false"
          weight: 100
        - destination:
            host: shelf.app.svc.cluster.local
            subset: canary
          headers:
            request:
              set:
                X-Canary: "true"
          weight: 0
```

I attempted to prototype this logic locally but encountered limitations due to missing type/function exports in current implementations. Any guidance or roadmap updates on this functionality would be greatly appreciated.
